version: '3.7'
services:
  backend:
    image: zhal73/pet-clinic-rest
    build: ./spring-petclinic-rest
    ports:
      - target: 9966      
        published: 9966
        protocol: tcp
  frontend:
    image: zhal73/pet-clinic-client
    build: ./spring-petclinic-angular
    ports:
      - target: 8080
        published: 8080
        protocol: tcp 
