apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: qajulyteam2/pet-clinic-rest
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: credentials
              key: db_uri
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: db_password
        ports:
        - containerPort: 9966
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9966
      targetPort: 9966
